name: Build CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linux:
    name: Linux build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Upload TheAirBlow.Thor.GUI binary
      uses: actions/upload-artifact@v2.2.4
      with:
        name: "TheAirBlow.Thor.GUI-linux"
        path: "TheAirBlow.Thor.GUI/bin/"
  windows:
    name: Windows build
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Upload TheAirBlow.Thor.GUI binary
      uses: actions/upload-artifact@v2.2.4
      with:
        name: "TheAirBlow.Thor.GUI-windows"
        path: "TheAirBlow.Thor.GUI/bin/"
  macos:
    name: MacOS build
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Upload TheAirBlow.Thor.GUI binary
      uses: actions/upload-artifact@v2.2.4
      with:
        name: "TheAirBlow.Thor.GUI-macos"
        path: "TheAirBlow.Thor.GUI/bin/"
